/// 1.3
### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films
### Create a movie
POST {{baseUrl}}/films 
Content-Type: application/json

{
    "title": "Interstellar",
    "duration": 169,
    "budget": 165000000,
"link": "https://www.imdb.com/title/tt0816692/"
}



### Read all films sorted by title (ascending)
GET {{baseUrl}}/films/?order=+title

### Read all films sorted by title (descending)
GET {{baseUrl}}/films/?order=-title