### Read all pizzas with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/pizzas

### Create a pizza
POST http://localhost:3000/pizzas 
Content-Type: application/json

{
    "title": "Magic Green",
    "content": "Epinards, Brocolis , Olives vertes , Basilic"
}

### READ ALL PIZZAS
GET http://localhost:3000/pizzas
### Read all pizzas sorted by title (ascending)
GET {{baseUrl}}/pizzas/?order=+title

### Read all pizzas sorted by title (descending)
GET {{baseUrl}}/pizzas/?order=-title

### Delete pizza identified by 2
DELETE {{baseUrl}}/pizzas/2